audit_header: false
title: Real Estate Training with Nick Mclean
description: 'Nick McLean, a top Real Estate Agent in Washington, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.'
show_custom_links: true
custom_links:
  - title: Events
    url: https://www.eventbrite.com/e/behind-the-n-tickets-46111800637

client:
  name: Nick McLean
  license_number:
  about_markdown: |
    Real Estate Greatness was created by Nick McLean to share to help the real estate industry grow and learn! Nick and his team of trainers at the Nick McLean Real Estate Group and friends will post videos with insights into what makes them GREAT along with FAILURES to avoid! This will give the world a chance to see how the Nick McLean Real Estate Group has grown their business each and every year while have fun in the process.
  market:
  brand: Nick Mclean Real Estate Group
  brokerage:
  address: 29 S Wenatchee Ave<br>Wenatchee, WA 98801
  phone: 509-670-5532
  phone_type:
  phone2:
  phone2_type:
  email: Nick@NickMcLean.com
  url: https://www.SellingWenatchee.com

CTAs:
  first_CTA_text: Join Our Team
  first_CTA_URL: https://www.sellingwenatchee.com/nick-mclean-real-estate-group-is-hiring/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: Looking to Build Your Real Estate Career?
    CTA_text: Let's talk about how we can take your business to new heights.
    CTA_link_text: Join Our Team
    CTA_url: https://www.sellingwenatchee.com/nick-mclean-real-estate-group-is-hiring/


lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/realestategreatnesswithnickmclean/
  linkedin_url: http://www.linkedin.com/pub/nick-mclean/17/b10/55a
  gplus_url: https://plus.google.com/b/104949022406662295619
  youtube_url: https://www.youtube.com/channel/UCZC5oZ1IPLqvfMwceU7ndtw
  twitter_url: https://twitter.com/nickmcleanre
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'North Central Washington Real Estate Podcast with Nick Mclean'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text:
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#a6734f'
  theme_color: '#231f20'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
